### ISSUE TITLE
newer git versions 2.17, 2.18, and 2.19

### ISSUE THREAD

**Issue by treacher** [iuscommunity-pkg/git2u#10]
In git2u 2.17.1 there is a fix for a vulnerability with Git submodules. See https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.17.1.txt for more information.

**Comment by carlwgeorge** [comment]
I'm having some compilation issues with 2.17.1.  However, the CVE fixes were also released as 2.16.4, which compiles just fine with no other changes (the current git2u version is 2.16.2).  So to get the security fix out there, I'll go ahead with 2.16.4 now ([spec file change](f77bececcf60db5ead9a8900dfaa47969bf5ab13)), and I'll tackle the bump to 2.17.1 later.  Builds are in progress and should hopefully finish in time for the push to the testing repos during tonight's automation.

**Comment by treacher** [comment]
We tested the new version of git on RHEL7 and found that it works as expected and that it's patched by running the following this post: https://staaldraad.github.io/post/2018-06-03-cve-2018-11235-git-rce/

**Comment by carlwgeorge** [comment]
Thanks for the feedback @treacher!  I'll go ahead and queue up the 2.16.4-1 release to move to the stable repos tonight.

**Comment by whereisaaron** [comment]
Thanks for updating git @carlwgeorge, there is now another security update needed. Luckily 2.16.x is still relevant, so could you test/queue 2.16.5?

https://nvd.nist.gov/vuln/detail/CVE-2018-17456

> Git before 2.14.5, 2.15.x before 2.15.3, 2.16.x before 2.16.5, 2.17.x before 2.17.2, 2.18.x before 2.18.1, and 2.19.x before 2.19.1 allows remote code execution during processing of a recursive "git clone" of a superproject if a .gitmodules file has a URL field beginning with a '-' character.

**Comment by carlwgeorge** [comment]
I still haven't had time to tackle the bump to 2.17.  I [bumped to 2.16.5](https://github.com/iuscommunity-pkg/git2u/commit/5463895d57b05e7e207b80a3d8fd05688695deef) as suggested.  That will get released to ius-testing soon.

This brings up a topic for discussion.  Originally IUS had a [git18](https://github.com/iuscommunity-pkg/git18) package.  We [EOL'ed it after we learned that upstream only supported the most recent version](https://lists.launchpad.net/ius-community/msg01187.html) (2.1.2 at the time).  Later we [created git2u](https://lists.launchpad.net/ius-community/msg01211.html) so that we could just follow the major version (i.e. 2.x.x).  However, more recently it's apparent that upstream does still maintain previous releases.  The fix for CVE-2018-17456 was released as [2.14.5](https://github.com/git/git/releases/tag/v2.14.5), [2.15.3](https://github.com/git/git/releases/tag/v2.15.3), [2.16.5](https://github.com/git/git/releases/tag/v2.16.5), [2.17.2](https://github.com/git/git/releases/tag/v2.17.2), [2.18.1](https://github.com/git/git/releases/tag/v2.18.1), and [2.19.1](https://github.com/git/git/releases/tag/v2.19.1).  Based on this I'm considering going back to that structure.  git2u can remain on 2.16, and I can create a new git219 package that follows the 2.19.x versions.  git217 and git218 could be created as well if necessary.  The "u" suffix should no longer be necessary, since SCL now uses either a "rh-" or "sclo-" prefix.

Unfortunately, there is no upstream policy regarding which previous version are still maintained, and for how long.  I contacted the upstream developers on IRC about this, and they confirmed that previous releases do get security and bug fixes, but entirely at the discretion of the developers, and on a case by case basis.  This means that releases with CVE fixes will have to be monitored closely, and once a version is no longer getting them (such as 2.13.x with this last CVE) any corresponding IUS package would be retired.

From the package maintenance perspective, this would make things easier, because each new package would be a fresh opportunity to rebase on the latest packaging improvements in the Fedora spec file.  Importing Fedora changes to our spec file has gotten to be rather cumbersome.

From the user perspective, users would no longer be able to stay on git2u long term, and would have to eventually manually switch to a newer packages.  Package EOLs would still be [announced as issues on iuscommunity/announce](https://github.com/iuscommunity/announce).  This isn't any different than other IUS packages, albeit without clear EOL dates.

Thoughts?

**Comment by wojciech-kopras** [comment]
According to the response ["IUS packages are designed to follow the upstream releases"](https://github.com/iuscommunity/announce/issues/9#issuecomment-421117297) I would think a good option is to keep only one version -- the most recent version that succeeded to build, sth like this algorithm:
```
for version in sortDescending(allVersions) {
    if build(version).success {
        return version
    }
}
```

Advantages:
- It's easier to keep one up-to-date than several..
- Users of RHEL/CentOS will have the newest possible version - goal of IUS achieved

**Comment by whereisaaron** [comment]
Thank @carlwgeorge. It sounds fine to me to have versioned packages again.

There is the minor issue that 'git218' is ambiguous between git 2.1.8 and git 2.18.x, but people can look at the package info if the are not sure about that.

Arguably 'git2u' should also update to the latest 2.x, as that was the original promise of that name. On the other hand, if you want people to switch of that package to a version-named package, then abandoning it at 2.16 will help with that 😄 

Of could you make 'git2u' an alias package for the latest e.g. right now 'git219'? That let's people target either a specific version or the latest.

**Comment by carlwgeorge** [comment]
@wojciech-kopras 

> According to the response "IUS packages are designed to follow the upstream releases"

Upstream is demonstrating that 2.16 is a maintained release.  This is similar to other IUS packages/upstreams (e.g. php71u and php72u).

> It's easier to keep one up-to-date than several..

It's more complicated than that, see my previous comment about import Fedora spec file changes.  In fact, maintaining packages for the older release branches will be significantly easier as they will will require fewer packaging changes.

> Users of RHEL/CentOS will have the newest possible version - goal of IUS achieved

A git219 package would also achieve this goal.

**Comment by carlwgeorge** [comment]
@whereisaaron 

> 'git218' is ambiguous

Yeah, we have the same confusion around mariadb100u/mariadb101u, nothing we can do about that.

> original promise of that name

Yup, that was the original intent, which I'd like to change.

> if you want people to switch of that package

I'm hoping that having `git2u-2.16.5-1`, `git218-2.18.1-1`, and `git219-2.19.1-1` available will be make the situation clear enough.

> make 'git2u' an alias package

IUS doesn't currently do this for any other packages.  One of the goals of IUS is to allow you choose an upstream branch, get updates to the latest of that branch, but not update to the next branch until you explicitly choose to.  Alias packages run contrary to that.  Even if we did decide to go that direction, doing it for just one group of packages doesn't make sense, it would need to be all or none.  While upgrading to the next branch continuously may be fine for git, it definitely isn't fine for things like mariadb.

As an aside, the virtual provides in IUS packages allow you to do this trick: `yum install redis --exclude redis`.  Currently that will install redis40u, but in the future it will install redis50.  That will give you the latest version at install time, but then pin you to that upstream branch.

**Comment by carlwgeorge** [comment]
[git2u-2.16.5-1](https://github.com/iuscommunity-pkg/git2u/releases/tag/2.16.5-1) will move to the testing repos during tonight's automation.

**Comment by vigiroux** [comment]
Thanks for providing these packages - they've been very helpful. Any news on git219? Need help "testing" them? Looking forward to using git protocol version 2 (introduced in 2.18).

**Comment by bukzor** [comment]
Same question. One of our systems relies on the new "type 2 protocol" introduced in git 2.17.

https://opensource.googleblog.com/2018/05/introducing-git-protocol-version-2.html

Would it be helpful to make a fresh ticket for just git 2.17? 

CC: @bulldozier

**Comment by carlwgeorge** [comment]
@bukzor Yes please, open a [wishlist request](https://github.com/iuscommunity/wishlist) for git217 and I'll get to it as soon as I can.

That will be the best path going forward, so I'm gonna close this issue out.

**Comment by carlwgeorge** [comment]
@bukzor Looks like git protocol version 2 was introduced in 2.18, not 2.17, so please make your request for git218 (or git219 or git220) if you want that.

**Comment by carlwgeorge** [comment]
I've created new git222 packages.  If anyone is interested in helping test them please share your feedback in [iusrepo/wishlist#241](https://github.com/iusrepo/wishlist/issues/241).
