### ISSUE TITLE
repo reference to package broken

### ISSUE THREAD

**Issue by dhellmann** [iuscommunity-pkg/git2u#13]
This is probably the wrong place to report this problem, but I couldn't figure out a better place reading the ius.io docs. Let me know if there's a forum or other better place to ask.

I get a 404 error for the git2u package on CentOS 7 after installing the RPM to configure the IUS repo and trying to install git2u.

The 404 is for https://repo.ius.io/7/x86_64/git2u-2.16.5-1.ius.centos7.x86_64.rpm

I see EL 7 versions of packages but not CentOS 7 in https://repo.ius.io/7/x86_64/packages/g/

This used to work somehow, so I'm not sure if something used to cause the EL 7 version of the RPM to be selected or if there did used to be CentOS 7 versions of the files.

Is CentOS 7 still a supported platform?

```
# yum  install git2u
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: mirror.wdc1.us.leaseweb.net
 * epel: mirror.us.leaseweb.net
 * extras: mirror.vcu.edu
 * updates: mirrors.mit.edu
7 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package git2u.x86_64 0:2.16.5-1.ius.centos7 will be installed
--> Processing Dependency: git2u-perl-Git = 2.16.5-1.ius.centos7 for package: git2u-2.16.5-1.ius.centos7.x86_64
--> Processing Dependency: perl(Git) for package: git2u-2.16.5-1.ius.centos7.x86_64
--> Processing Dependency: perl(Git::I18N) for package: git2u-2.16.5-1.ius.centos7.x86_64
--> Running transaction check
---> Package git2u-perl-Git.noarch 0:2.16.5-1.ius.centos7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================================================================================================================================================================
 Package                                                  Arch                                             Version                                                           Repository                                     Size
=================================================================================================================================================================================================================================
Installing:
 git2u                                                    x86_64                                           2.16.5-1.ius.centos7                                              ius                                           1.1 M
Installing for dependencies:
 git2u-perl-Git                                           noarch                                           2.16.5-1.ius.centos7                                              ius                                            67 k

Transaction Summary
=================================================================================================================================================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 1.1 M
Installed size: 2.4 M
Is this ok [y/d/N]: y
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
git2u-2.16.5-1.ius.centos7.x86 FAILED
https://repo.ius.io/7/x86_64/git2u-2.16.5-1.ius.centos7.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found                                                                                     ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

git2u-perl-Git-2.16.5-1.ius.ce FAILED
https://repo.ius.io/7/x86_64/git2u-perl-Git-2.16.5-1.ius.centos7.noarch.rpm: [Errno 14] HTTPS Error 404 - Not Found                                                                            ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.


Error downloading packages:
  git2u-2.16.5-1.ius.centos7.x86_64: [Errno 256] No more mirrors to try.
  git2u-perl-Git-2.16.5-1.ius.centos7.noarch: [Errno 256] No more mirrors to try.
```

**Comment by carlwgeorge** [comment]
This works just fine to report issues specific to a single package.  For a faster response I'd recommend joining our IRC channel, `#ius` on Freenode.  We've been making some infrastructure changes as detailed [here](https://github.com/iusrepo/infrastructure/issues/14).  Part of that is only building one set of packages for both RHEL and CentOS, similar to how EPEL does it.  You shouldn't be seeing an error like that.  How have you configured the IUS repo?  

* If you are using `ius-release-1.0-15.ius.el7`, you should be pointing at the old infrastructure, which uses the `mirrorlist` parameter to point you to our mirrorlist API, which will direct you to the path `/stable/CentOS/7/x86_64/` on one of our mirrors, which will include the file `git2u-2.16.5-1.ius.centos7.x86_64.rpm`.

* If you are using `ius-release-2-1.el7.ius`, you should be pointed at the repo.ius.io CDN which doesn't have CentOS packages.  The URL you mentioned should 404 because that file doesn't exist on the CDN.  Yum should be pointing you to https://repo.ius.io/7/x86_64/packages/g/git2u-2.16.5-1.ius.el7.x86_64.rpm.

* If you have configured IUS in some other way, please share how.

For what it's worth, in a fresh CentOS container, I installed https://repo.ius.io/ius-release-el7.rpm (`ius-release-2-1.el7.ius`) and was able to install git2u without a problem.

**Comment by dhellmann** [comment]
I installed the ius repo settings by going to https://ius.io/GettingStarted/ and copying the URL associated with the link for CentOS 7 at the bottom of the page, which gave me https://centos7.iuscommunity.org/ius-release.rpm. Then I ran "yum install https://centos7.iuscommunity.org/ius-release.rpm".

That gave me an ius.repo file containing:

```
# cat /etc/yum.repos.d/ius.repo
[ius]
name = IUS for Enterprise Linux 7 - $basearch
baseurl = https://repo.ius.io/7/$basearch/
enabled = 1
repo_gpgcheck = 0
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7

[ius-debuginfo]
name = IUS for Enterprise Linux 7 - $basearch - Debug
baseurl = https://repo.ius.io/7/$basearch/debug/
enabled = 0
repo_gpgcheck = 0
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7

[ius-source]
name = IUS for Enterprise Linux 7 - Source
baseurl = https://repo.ius.io/7/src/
enabled = 0
repo_gpgcheck = 0
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7
```

So, I think you're saying I should have selected the EL7 repo package instead of the one for CentOS 7. Is that right?

**Comment by carlwgeorge** [comment]
https://centos7.iuscommunity.org/ius-release.rpm is the old link, but it redirects to the new https://repo.ius.io/ius-release-el7.rpm link.  It would make no difference using https://rhel7.iuscommunity.org/ius-release.rpm because that also redirects to https://repo.ius.io/ius-release-el7.rpm.  I do still need to update the website, but the redirect are working as intended.

Your `ius.repo` file confirms the CDN is configured correctly.  The repodata in https://repo.ius.io/7/x86_64/ should not have pointed you at `git2u-2.16.5-1.ius.centos7.x86_64.rpm`.  I verified manually that it is currently pointing at `git2u-2.16.2-1.ius.el7.x86_64.rpm`.  I'm not sure how you saw the error you did.  Does it work if you run `yum clean all` to force yum to fetch the current repodata?

**Comment by dhellmann** [comment]
OK, running "yum clean" does fix the issue. I suspect this all came up because at some point I removed  the old repo settings without cleaning, and then added them back later. Thanks for the debugging suggestion!
