### ISSUE TITLE
Installing Over Compiled Git

### ISSUE THREAD

**Issue by omento** [iuscommunity-pkg/git2u#7]
Hey guys, thanks for creating this! The IUS repo's have saved me time and time again.

That being said, I'm running into a bit of an issue with installing `git2u`. First I had to install the `yum-plugin-replace` addition in order to bypass the errors with `git-core` and `git-perl` both of which were v1.8. This is strange because I didn't think they were installed as I would compile Git from source (running `git --version` would always return 2.x).

After getting through that when checking the version it still returns the self-compiled version of Git, rather than 2.13.0 from the repo. I have no idea how to remove this so that the IUS install will become the system default. Any pointers? I'm using CentOS 7.3 if it makes a difference.

**Comment by carlwgeorge** [comment]
By design, git2u packages conflict with their stock counterparts, because they have files in the same locations.  Please read over our [usage guide](https://ius.io/Usage/) for a more thorough explanation.

It sounds like the custom compiled version of git has placed it's executable earlier in your `$PATH` than git2u's `/usr/bin/git`.  Try running the command `type -a git` to find out exactly what is being run.  That should point you in the right direction.  You probably want to remove all the files from your custom compiled git, but I don't know how to help you with that.

**Comment by omento** [comment]
@carlwgeorge Thanks for that, I've never used the `type` command before. Everything was stored in `/usr/local/` and its subdirectories. Removing them fixed the issue, and everything seems to be working fine. Thanks again!

**Comment by carlwgeorge** [comment]
No problem.  You could also run the command `which git` for the same result, which is a little more widely known.  I recommend `type` however because it has the advantage of the `-a` flag that will also show you aliases and shell functions.
